# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RLRecords.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RLRecords.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\252\002\rSlither.Proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fRLRecords.proto\"I\n\x07Request\x12\x0c\n\x04\x44ied\x18\x01 \x01(\x08\x12\x11\n\tTimeStamp\x18\x02 \x01(\x03\x12\x0e\n\x06Length\x18\x03 \x01(\x05\x12\r\n\x05Image\x18\x04 \x03(\x02\"\"\n\x08Response\x12\x16\n\x06\x41\x63tion\x18\x01 \x01(\x0e\x32\x06.Moves\"8\n\rRewardRequest\x12\x17\n\x05state\x18\x01 \x01(\x0b\x32\x08.Request\x12\x0e\n\x06reward\x18\x02 \x01(\x02\"\t\n\x07Nothing*P\n\x05Moves\x12\x08\n\x04Left\x10\x00\x12\t\n\x05Right\x10\x01\x12\t\n\x05\x42oost\x10\x02\x12\r\n\tBoostLeft\x10\x03\x12\x0e\n\nBoostRight\x10\x04\x12\x08\n\x04Wait\x10\x05\x32x\n\x0eSlitherTrainer\x12\x1f\n\x08NextMove\x12\x08.Request\x1a\t.Response\x12!\n\x05Reset\x12\x0e.RewardRequest\x1a\x08.Nothing\x12\"\n\x06Reward\x12\x0e.RewardRequest\x1a\x08.NothingB\x10\xaa\x02\rSlither.Protob\x06proto3'
)

_MOVES = _descriptor.EnumDescriptor(
  name='Moves',
  full_name='Moves',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Left', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Right', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Boost', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BoostLeft', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BoostRight', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Wait', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=199,
  serialized_end=279,
)
_sym_db.RegisterEnumDescriptor(_MOVES)

Moves = enum_type_wrapper.EnumTypeWrapper(_MOVES)
Left = 0
Right = 1
Boost = 2
BoostLeft = 3
BoostRight = 4
Wait = 5



_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Died', full_name='Request.Died', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='TimeStamp', full_name='Request.TimeStamp', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Length', full_name='Request.Length', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Image', full_name='Request.Image', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=92,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Action', full_name='Response.Action', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=128,
)


_REWARDREQUEST = _descriptor.Descriptor(
  name='RewardRequest',
  full_name='RewardRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='RewardRequest.state', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reward', full_name='RewardRequest.reward', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=186,
)


_NOTHING = _descriptor.Descriptor(
  name='Nothing',
  full_name='Nothing',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=197,
)

_RESPONSE.fields_by_name['Action'].enum_type = _MOVES
_REWARDREQUEST.fields_by_name['state'].message_type = _REQUEST
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['RewardRequest'] = _REWARDREQUEST
DESCRIPTOR.message_types_by_name['Nothing'] = _NOTHING
DESCRIPTOR.enum_types_by_name['Moves'] = _MOVES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'RLRecords_pb2'
  # @@protoc_insertion_point(class_scope:Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'RLRecords_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)

RewardRequest = _reflection.GeneratedProtocolMessageType('RewardRequest', (_message.Message,), {
  'DESCRIPTOR' : _REWARDREQUEST,
  '__module__' : 'RLRecords_pb2'
  # @@protoc_insertion_point(class_scope:RewardRequest)
  })
_sym_db.RegisterMessage(RewardRequest)

Nothing = _reflection.GeneratedProtocolMessageType('Nothing', (_message.Message,), {
  'DESCRIPTOR' : _NOTHING,
  '__module__' : 'RLRecords_pb2'
  # @@protoc_insertion_point(class_scope:Nothing)
  })
_sym_db.RegisterMessage(Nothing)


DESCRIPTOR._options = None

_SLITHERTRAINER = _descriptor.ServiceDescriptor(
  name='SlitherTrainer',
  full_name='SlitherTrainer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=281,
  serialized_end=401,
  methods=[
  _descriptor.MethodDescriptor(
    name='NextMove',
    full_name='SlitherTrainer.NextMove',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Reset',
    full_name='SlitherTrainer.Reset',
    index=1,
    containing_service=None,
    input_type=_REWARDREQUEST,
    output_type=_NOTHING,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Reward',
    full_name='SlitherTrainer.Reward',
    index=2,
    containing_service=None,
    input_type=_REWARDREQUEST,
    output_type=_NOTHING,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SLITHERTRAINER)

DESCRIPTOR.services_by_name['SlitherTrainer'] = _SLITHERTRAINER

# @@protoc_insertion_point(module_scope)
