---
name: SlitherTrainer unit tests
on: push

jobs:
  UnitTestTrain:
    name: Run Unit tests for training methods
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python env
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install deps
        run: |
          cd SlitherTrainer
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Run unit tests
        run: |
          cd SlitherTrainer
          python -m unittest tests
